moving modules to wdl
oicr-gsi/wgsMetrics pull request #9
Opened 2023-07-04 12:47 UTC by gavin-peng

https://jira.oicr.on.ca/browse/GRD-656 wdl completed and validated

2023-07-04 15:23 UTC, pruzanov commented
Please update CHANGELOG as well

2023-07-04 15:23 UTC, pruzanov requested changes
CHANGELOG needs to be updated

2023-07-04 16:25 UTC, gavin-peng commented
CHANGELOG updated

2023-07-04 23:18 UTC, pruzanov approved these changes

2023-07-04 23:18 UTC, pruzanov commented on CHANGELOG.md
>  # Unreleased
This "Unreleased" record is not needed (or is it  misplaced?)

2023-07-05 15:27 UTC, gavin-peng commented on CHANGELOG.md
>  # Unreleased
Removed. yes, not needed.

2023-07-05 15:27 UTC, merged